name: Haskell CI (Cabal)

on:
    push:
        branches: [ "main", "migrate-to-cabal" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup Haskell (GHC & Cabal)
              uses: haskell-actions/setup@v2
              with:
                ghc-version: '9.8.1'
                cabal-version: 'latest'

            - name: Update Cabal index
              run: cabal update

            - name: Install hpack
              run: cabal install hpack --overwrite-policy=always

            - name: Generate .cabal file
              run: hpack

            - name: Cache Cabal dependencies
              uses: actions/cache@v5
              with:
                path: |
                  ~/.cabal/store
                  dist-newstyle
                key: ${{ runner.os }}-cabal-${{ hashFiles('package.yaml') }}
                restore-keys: |
                  ${{ runner.os }}-cabal-

            - name: Build project
              run: cabal build --enable-tests

            - name: Run Tasty Tests
              run: cabal test --test-show-details=direct
